package sistem_tehnicki_pregled.model.enums;

import lombok.Getter;

@Getter
public enum VehicleModel {
    ABARTH_500("500"),
    ABARTH_595("595"),
    ABARTH_695("695"),
    ALFA_ROMEO_GIULIA("Giulia"),
    ALFA_ROMEO_GIULIETTA("Giulietta"),
    ALFA_ROMEO_STELVIO("Stelvio"),
    ALFA_ROMEO_TONALE("Tonale"),
    ALFA_ROMEO_MITO("MiTo"),
    ALFA_ROMEO_159("159"),
    ALFA_ROMEO_147("147"),
    AUDI_A1("A1"),
    AUDI_A3("A3"),
    AUDI_A4("A4"),
    AUDI_A5("A5"),
    AUDI_A6("A6"),
    AUDI_A7("A7"),
    AUDI_A8("A8"),
    AUDI_Q2("Q2"),
    AUDI_Q3("Q3"),
    AUDI_Q5("Q5"),
    AUDI_Q7("Q7"),
    AUDI_Q8("Q8"),
    AUDI_TT("TT"),
    AUDI_E_TRON("e-tron"),
    BMW_SERIJA_1("Serija 1"),
    BMW_SERIJA_2("Serija 2"),
    BMW_SERIJA_3("Serija 3"),
    BMW_SERIJA_4("Serija 4"),
    BMW_SERIJA_5("Serija 5"),
    BMW_SERIJA_6("Serija 6"),
    BMW_SERIJA_7("Serija 7"),
    BMW_X1("X1"),
    BMW_X2("X2"),
    BMW_X3("X3"),
    BMW_X4("X4"),
    BMW_X5("X5"),
    BMW_X6("X6"),
    BMW_X7("X7"),
    BMW_Z4("Z4"),
    BMW_I3("i3"),
    BMW_I4("i4"),
    BMW_IX("iX"),
    CHEVROLET_AVEO("Aveo"),
    CHEVROLET_CAPTIVA("Captiva"),
    CHEVROLET_CRUZE("Cruze"),
    CHEVROLET_MALIBU("Malibu"),
    CHEVROLET_ORLANDO("Orlando"),
    CHEVROLET_SPARK("Spark"),
    CHEVROLET_TRAX("Trax"),
    CHRYSLER_300C("300C"),
    CHRYSLER_PACIFICA("Pacifica"),
    CHRYSLER_VOYAGER("Voyager"),
    CITROEN_C1("C1"),
    CITROEN_C3("C3"),
    CITROEN_C4("C4"),
    CITROEN_C5("C5"),
    CITROEN_BERLINGO("Berlingo"),
    CITROEN_C3_AIRCROSS("C3 Aircross"),
    CITROEN_C5_AIRCROSS("C5 Aircross"),
    CITROEN_C_ELYSEE("C-Elysee"),
    CUPRA_ATECA("Ateca"),
    CUPRA_BORN("Born"),
    CUPRA_FORMENTOR("Formentor"),
    CUPRA_LEON("Leon"),
    CUPRA_TAVASCAN("Tavascan"),
    DACIA_DOKKER("Dokker"),
    DACIA_DUSTER("Duster"),
    DACIA_JOGGER("Jogger"),
    DACIA_LODGY("Lodgy"),
    DACIA_LOGAN("Logan"),
    DACIA_SANDERO("Sandero"),
    DACIA_SPRING("Spring"),
    DODGE_CALIBER("Caliber"),
    DODGE_JOURNEY("Journey"),
    DODGE_NITRO("Nitro"),
    DS_DS_3("DS 3"),
    DS_DS_4("DS 4"),
    DS_DS_7("DS 7"),
    FIAT_500("500"),
    FIAT_500L("500L"),
    FIAT_500X("500X"),
    FIAT_BRAVO("Bravo"),
    FIAT_DOBLO("Doblo"),
    FIAT_PANDA("Panda"),
    FIAT_PUNTO("Punto"),
    FIAT_TIPO("Tipo"),
    FIAT_FREEMONT("Freemont"),
    FORD_B_MAX("B-Max"),
    FORD_C_MAX("C-Max"),
    FORD_ECOSPORT("EcoSport"),
    FORD_EDGE("Edge"),
    FORD_EXPLORER("Explorer"),
    FORD_FIESTA("Fiesta"),
    FORD_FOCUS("Focus"),
    FORD_FUSION("Fusion"),
    FORD_GALAXY("Galaxy"),
    FORD_KA("Ka"),
    FORD_KUGA("Kuga"),
    FORD_MONDEO("Mondeo"),
    FORD_MUSTANG("Mustang"),
    FORD_PUMA("Puma"),
    FORD_RANGER("Ranger"),
    FORD_S_MAX("S-Max"),
    FORD_TRANSIT("Transit"),
    HONDA_ACCORD("Accord"),
    HONDA_CITY("City"),
    HONDA_CIVIC("Civic"),
    HONDA_CR_V("CR-V"),
    HONDA_HR_V("HR-V"),
    HONDA_JAZZ("Jazz"),
    HONDA_PILOT("Pilot"),
    HONDA_ZR_V("ZR-V"),
    HYUNDAI_ACCENT("Accent"),
    HYUNDAI_BAYON("Bayon"),
    HYUNDAI_ELANTRA("Elantra"),
    HYUNDAI_I10("i10"),
    HYUNDAI_I20("i20"),
    HYUNDAI_I30("i30"),
    HYUNDAI_I40("i40"),
    HYUNDAI_IONIQ("Ioniq"),
    HYUNDAI_IONIQ_5("Ioniq 5"),
    HYUNDAI_IONIQ_6("Ioniq 6"),
    HYUNDAI_IX35("ix35"),
    HYUNDAI_KONA("Kona"),
    HYUNDAI_SANTA_FE("Santa Fe"),
    HYUNDAI_SONATA("Sonata"),
    HYUNDAI_TUCSON("Tucson"),
    JAGUAR_E_PACE("E-Pace"),
    JAGUAR_F_PACE("F-Pace"),
    JAGUAR_F_TYPE("F-Type"),
    JAGUAR_I_PACE("I-Pace"),
    JAGUAR_XE("XE"),
    JAGUAR_XF("XF"),
    JAGUAR_XJ("XJ"),
    JEEP_CHEROKEE("Cherokee"),
    JEEP_COMPASS("Compass"),
    JEEP_GRAND_CHEROKEE("Grand Cherokee"),
    JEEP_PATRIOT("Patriot"),
    JEEP_RENEGADE("Renegade"),
    JEEP_WRANGLER("Wrangler"),
    KIA_CEED("Ceed"),
    KIA_CERATO("Cerato"),
    KIA_EV6("EV6"),
    KIA_NIRO("Niro"),
    KIA_OPTIMA("Optima"),
    KIA_PICANTO("Picanto"),
    KIA_RIO("Rio"),
    KIA_SORENTO("Sorento"),
    KIA_SOUL("Soul"),
    KIA_SPORTAGE("Sportage"),
    KIA_STONIC("Stonic"),
    KIA_XCEED("XCeed"),
    LADA_GRANTA("Granta"),
    LADA_KALINA("Kalina"),
    LADA_NIVA("Niva"),
    LADA_PRIORA("Priora"),
    LADA_VESTA("Vesta"),
    LADA_XRAY("XRAY"),
    LAND_ROVER_DEFENDER("Defender"),
    LAND_ROVER_DISCOVERY("Discovery"),
    LAND_ROVER_DISCOVERY_SPORT("Discovery Sport"),
    LAND_ROVER_FREELANDER("Freelander"),
    LAND_ROVER_RANGE_ROVER("Range Rover"),
    LAND_ROVER_RANGE_ROVER_EVOQUE("Range Rover Evoque"),
    LAND_ROVER_RANGE_ROVER_SPORT("Range Rover Sport"),
    LAND_ROVER_RANGE_ROVER_VELAR("Range Rover Velar"),
    LEXUS_CT("CT"),
    LEXUS_ES("ES"),
    LEXUS_GS("GS"),
    LEXUS_IS("IS"),
    LEXUS_NX("NX"),
    LEXUS_RX("RX"),
    LEXUS_UX("UX"),
    MAZDA_2("2"),
    MAZDA_3("3"),
    MAZDA_5("5"),
    MAZDA_6("6"),
    MAZDA_CX_3("CX-3"),
    MAZDA_CX_30("CX-30"),
    MAZDA_CX_5("CX-5"),
    MAZDA_CX_60("CX-60"),
    MAZDA_MX_5("MX-5"),
    MERCEDES_BENZ_A_KLASA("A-Klasa"),
    MERCEDES_BENZ_B_KLASA("B-Klasa"),
    MERCEDES_BENZ_C_KLASA("C-Klasa"),
    MERCEDES_BENZ_CLA("CLA"),
    MERCEDES_BENZ_CLS("CLS"),
    MERCEDES_BENZ_E_KLASA("E-Klasa"),
    MERCEDES_BENZ_G_KLASA("G-Klasa"),
    MERCEDES_BENZ_GLA("GLA"),
    MERCEDES_BENZ_GLB("GLB"),
    MERCEDES_BENZ_GLC("GLC"),
    MERCEDES_BENZ_GLE("GLE"),
    MERCEDES_BENZ_GLK("GLK"),
    MERCEDES_BENZ_GLS("GLS"),
    MERCEDES_BENZ_S_KLASA("S-Klasa"),
    MERCEDES_BENZ_SLK("SLK"),
    MERCEDES_BENZ_V_KLASA("V-Klasa"),
    MERCEDES_BENZ_SPRINTER("Sprinter"),
    MINI_CLUBMAN("Clubman"),
    MINI_COUNTRYMAN("Countryman"),
    MINI_COOPER("Cooper"),
    MINI_COOPER_S("Cooper S"),
    MINI_PACEMAN("Paceman"),
    MINI_ONE("One"),
    MITSUBISHI_ASX("ASX"),
    MITSUBISHI_COLT("Colt"),
    MITSUBISHI_ECLIPSE_CROSS("Eclipse Cross"),
    MITSUBISHI_L200("L200"),
    MITSUBISHI_LANCER("Lancer"),
    MITSUBISHI_OUTLANDER("Outlander"),
    MITSUBISHI_PAJERO("Pajero"),
    MITSUBISHI_SPACE_STAR("Space Star"),
    NISSAN_JUKE("Juke"),
    NISSAN_LEAF("Leaf"),
    NISSAN_MICRA("Micra"),
    NISSAN_MURANO("Murano"),
    NISSAN_NAVARA("Navara"),
    NISSAN_NOTE("Note"),
    NISSAN_PATHFINDER("Pathfinder"),
    NISSAN_PRIMERA("Primera"),
    NISSAN_PULSAR("Pulsar"),
    NISSAN_QASHQAI("Qashqai"),
    NISSAN_TERRANO("Terrano"),
    NISSAN_TIIDA("Tiida"),
    NISSAN_X_TRAIL("X-Trail"),
    OPEL_ADAM("Adam"),
    OPEL_AGILA("Agila"),
    OPEL_ASTRA("Astra"),
    OPEL_COMBO("Combo"),
    OPEL_CORSA("Corsa"),
    OPEL_CROSSLAND("Crossland"),
    OPEL_GRANDLAND("Grandland"),
    OPEL_INSIGNIA("Insignia"),
    OPEL_KARL("Karl"),
    OPEL_MERIVA("Meriva"),
    OPEL_MOKKA("Mokka"),
    OPEL_OMEGA("Omega"),
    OPEL_SIGNUM("Signum"),
    OPEL_VECTRA("Vectra"),
    OPEL_VIVARO("Vivaro"),
    OPEL_ZAFIRA("Zafira"),
    PEUGEOT_106("106"),
    PEUGEOT_107("107"),
    PEUGEOT_108("108"),
    PEUGEOT_2008("2008"),
    PEUGEOT_206("206"),
    PEUGEOT_207("207"),
    PEUGEOT_208("208"),
    PEUGEOT_3008("3008"),
    PEUGEOT_301("301"),
    PEUGEOT_307("307"),
    PEUGEOT_308("308"),
    PEUGEOT_406("406"),
    PEUGEOT_407("407"),
    PEUGEOT_5008("5008"),
    PEUGEOT_508("508"),
    PEUGEOT_PARTNER("Partner"),
    PEUGEOT_RCZ("RCZ"),
    PORSCHE_911("911"),
    PORSCHE_BOXSTER("Boxster"),
    PORSCHE_CAYENNE("Cayenne"),
    PORSCHE_CAYMAN("Cayman"),
    PORSCHE_MACAN("Macan"),
    PORSCHE_PANAMERA("Panamera"),
    PORSCHE_TAYCAN("Taycan"),
    RENAULT_CAPTUR("Captur"),
    RENAULT_CLIO("Clio"),
    RENAULT_ESPACE("Espace"),
    RENAULT_FLUENCE("Fluence"),
    RENAULT_KADJAR("Kadjar"),
    RENAULT_KANGOO("Kangoo"),
    RENAULT_KOLEOS("Koleos"),
    RENAULT_LAGUNA("Laguna"),
    RENAULT_MEGANE("Megane"),
    RENAULT_SCENIC("Scenic"),
    RENAULT_TALISMAN("Talisman"),
    RENAULT_TWINGO("Twingo"),
    RENAULT_ZOE("Zoe"),
    SEAT_ALHAMBRA("Alhambra"),
    SEAT_ALTEA("Altea"),
    SEAT_ARONA("Arona"),
    SEAT_ATECA("Ateca"),
    SEAT_CORDOBA("Cordoba"),
    SEAT_EXEO("Exeo"),
    SEAT_IBIZA("Ibiza"),
    SEAT_LEON("Leon"),
    SEAT_MII("Mii"),
    SEAT_TARRACO("Tarraco"),
    SEAT_TOLEDO("Toledo"),
    SKODA_CITIGO("Citigo"),
    SKODA_FABIA("Fabia"),
    SKODA_FELICIA("Felicia"),
    SKODA_KAMIQ("Kamiq"),
    SKODA_KAROQ("Karoq"),
    SKODA_KODIAQ("Kodiaq"),
    SKODA_OCTAVIA("Octavia"),
    SKODA_RAPID("Rapid"),
    SKODA_ROOMSTER("Roomster"),
    SKODA_SCALA("Scala"),
    SKODA_SUPERB("Superb"),
    SKODA_YETI("Yeti"),
    SMART_FORFOUR("Forfour"),
    SMART_FORTWO("Fortwo"),
    SUBARU_FORESTER("Forester"),
    SUBARU_IMPREZA("Impreza"),
    SUBARU_LEGACY("Legacy"),
    SUBARU_OUTBACK("Outback"),
    SUBARU_XV("XV"),
    SUZUKI_ALTO("Alto"),
    SUZUKI_BALENO("Baleno"),
    SUZUKI_GRAND_VITARA("Grand Vitara"),
    SUZUKI_IGNIS("Ignis"),
    SUZUKI_JIMNY("Jimny"),
    SUZUKI_S_CROSS("S-Cross"),
    SUZUKI_SWIFT("Swift"),
    SUZUKI_SX4("SX4"),
    SUZUKI_VITARA("Vitara"),
    SUZUKI_WAGON_R("Wagon R"),
    TESLA_MODEL_3("Model 3"),
    TESLA_MODEL_S("Model S"),
    TESLA_MODEL_X("Model X"),
    TESLA_MODEL_Y("Model Y"),
    TOYOTA_AURIS("Auris"),
    TOYOTA_AVENSIS("Avensis"),
    TOYOTA_AYGO("Aygo"),
    TOYOTA_C_HR("C-HR"),
    TOYOTA_CAMRY("Camry"),
    TOYOTA_COROLLA("Corolla"),
    TOYOTA_HILUX("Hilux"),
    TOYOTA_LAND_CRUISER("Land Cruiser"),
    TOYOTA_PRIUS("Prius"),
    TOYOTA_RAV4("RAV4"),
    TOYOTA_YARIS("Yaris"),
    TOYOTA_BZ4X("bZ4X"),
    VOLKSWAGEN_ARTEON("Arteon"),
    VOLKSWAGEN_BEETLE("Beetle"),
    VOLKSWAGEN_BORA("Bora"),
    VOLKSWAGEN_CADDY("Caddy"),
    VOLKSWAGEN_GOLF("Golf"),
    VOLKSWAGEN_ID_3("ID.3"),
    VOLKSWAGEN_ID_4("ID.4"),
    VOLKSWAGEN_ID_5("ID.5"),
    VOLKSWAGEN_JETTA("Jetta"),
    VOLKSWAGEN_PASSAT("Passat"),
    VOLKSWAGEN_POLO("Polo"),
    VOLKSWAGEN_SHARAN("Sharan"),
    VOLKSWAGEN_T_CROSS("T-Cross"),
    VOLKSWAGEN_T_ROC("T-Roc"),
    VOLKSWAGEN_TIGUAN("Tiguan"),
    VOLKSWAGEN_TOUAREG("Touareg"),
    VOLKSWAGEN_TOURAN("Touran"),
    VOLKSWAGEN_UP("Up!"),
    VOLVO_C30("C30"),
    VOLVO_C70("C70"),
    VOLVO_S40("S40"),
    VOLVO_S60("S60"),
    VOLVO_S80("S80"),
    VOLVO_S90("S90"),
    VOLVO_V40("V40"),
    VOLVO_V50("V50"),
    VOLVO_V60("V60"),
    VOLVO_V70("V70"),
    VOLVO_V90("V90"),
    VOLVO_XC40("XC40"),
    VOLVO_XC60("XC60"),
    VOLVO_XC70("XC70"),
    VOLVO_XC90("XC90"),
    ZASTAVA_10("10"),
    ZASTAVA_101("101"),
    ZASTAVA_128("128"),
    ZASTAVA_750("750"),
    ZASTAVA_FLORIDA("Florida"),
    ZASTAVA_KORAL("Koral"),
    ZASTAVA_YUGO("Yugo");

    private final String displayName;

    VehicleModel(String displayName) {
        this.displayName = displayName;
    }

}
