export enum LightBulbType {
  NON_HALOGEN = 'NON_HALOGEN',
  HALOGEN_SINGLE_FILAMENT = 'HALOGEN_SINGLE_FILAMENT',
  HALOGEN_DUAL_FILAMENT = 'HALOGEN_DUAL_FILAMENT',
  GAS_DISCHARGE = 'GAS_DISCHARGE',
}
